### PR TITLE
Use `checklist` for `SignificanceCriteria` and `ComparativeCriteria`

### PR DESCRIPTION
**Pull request by kehh**
* The previous `render` value was incorrect - that is for a single checkbox
* Also bump the maxAttributesPerRow to the commonly used one
* set `<setting name="maxColumns">6</setting>` so checkboxes are 6 in a row

### CODE REVIEW

**Comment by kehh** [comment]
Just so you can see them
checkboxes

**Comment by leftclickben** [comment]
The layout could be better, the labels are wrapping (e.g. "Interpretive Potential").

Wondering whether `maxColumns = 3` would be better?  Or do you plan on fixing this with CSS?

Otherwise this looks good.

**Comment by kehh** [comment]
I'll do `maxColumns = 3` and see how that goes

**Comment by kehh** [comment]
ok here you go

**Pull request merged**
